<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 TRANSITIONAL//EN">
<html>
	<head>
		<title>UnitTestExceptionKFS - REALbasic Common KFS BSD Library Documentation</title>
		<link rel="stylesheet" href="../../style.css">
	</head>
	<body>
		<h1>REALbasic Common KFS BSD Library Documentation</h1>
		<div id="tnb" class="hlinks">
			<a href="../../index.html">Index</a>
			<a class="act">Core</a>
			<a href="../../download.html">Download</a>
			<a href="../../usingwithvc.html">Using with Git</a>
			<a href="../../usingwithrb.html">Using with REAL Studio</a>
		</div>
		<div class=docblock>
			<h2>UnitTestExceptionKFS <span class=cd>(Inherits from RuntimeException)</span></h2>
			<p>The UnitTestExceptionKFS method represents a problem with a test case.  It could either be a failed assertion, such as "Expected True but found False", or it can be an uncaught exception such as "An unhandled IOException was raised sometime before assertion number 4".</p>
			
			<h2>Shared Methods Used as Constructors</h2>
			<div class="attrlist">
				<div class="unit">
					<h1>NewExceptionFromAssertionFailure</h1>
					<h2>NewExceptionFromAssertionFailure( testClass As UnitTestBaseClassKFS, failure As String, msg As String = "" ) As UnitTestExceptionKFS</h2>
					<h2>NewExceptionFromAssertionFailure( testClass As UnitTestBaseClassKFS, expectedValue As Variant, foundValue As Variant, msg As String = "" ) As UnitTestExceptionKFS</h2>
					<p>Creates a new UnitTestExceptionKFS that represents the given assertion failure.</p>
				</div>
				<div class="unit">
					<h1>NewExceptionFromException</h1>
					<h2>NewExceptionFromException( testClass As UnitTestBaseClassKFS, e As RuntimeException, msg As String = "" ) As UnitTestExceptionKFS</h2>
					<p>Creates a new UnitTestExceptionKFS that represents the given exception, assuming it was caught.  This makes the exception look more like a failed assertion and less like an uncaught exception.</p>
				</div>
				<div class="unit">
					<h1>NewExceptionFromUncaughtException</h1>
					<h2>NewExceptionFromUncaughtException( testClass As UnitTestBaseClassKFS, e As RuntimeException, msg As String = "" ) As UnitTestExceptionKFS</h2>
					<p>Creates a new UnitTestExceptionKFS that represents the given exception, assuming is was not caught.</p>
				</div>
			</div>
			
			<h2>Methods</h2>
			<div class="attrlist">
				<div class="unit">
					<h1>GetComponentData</h1>
					<h2>GetComponentData( ByRef scenario As UnitTestArbiterKFS.UnitTestExceptionScenarios, ByRef className As String, ByRef raw_criteria As String, ByRef errNumber As Integer, ByRef expln As String, ByRef assNum As Integer )</h2>
					<p>Returns through the parameters the component data of the exception.  Used by the UnitTestArbiterKFS class when it copies an exception into its internal database.</p>
				</div>
			</div>
			
			<h2>Shared Methods</h2>
			<div class="attrlist">
				<div class="unit">
					<h1>FormatCriteria</h1>
					<h2>FormatCriteria( scenario As UnitTestArbiterKFS.UnitTestExceptionScenarios, className As String, raw_criteria As String, errNumber As Integer, assNum As Integer ) As String</h2>
					<p>Returns a human readable description of the criteria of an exception with the given characteristics.  Used by the UnitTestArbiterKFS class to reassemble a criteria description from its component pieces that are stored in its internal database.</p>
				</div>
				<div class="unit">
					<h1>FormatMessage</h1>
					<h2>FormatMessage( scenario As UnitTestArbiterKFS.UnitTestExceptionScenarios, className As String, raw_criteria As String, errNumber As Integer, expln As String, assNum As Integer ) As String</h2>
					<p>Returns a human readable description of the overall message of an exception with the given characteristics.  Used by the UnitTestArbiterKFS class to reassemble an exception message from its component pieces that are stored in its internal database.</p>
				</div>
			</div>
			
			<h2>Properties</h2>
			<div class="attrlist">
				<div class="unit readonly">
					<h1>AssertionNumber</h1>
					<h2>AssertionNumber() As Integer</h2>
					<p>Returns the assertion number of the failed assertion, or the assertion number that the exception occurred before.  Check the IsAFailedAssertion property to tell which is which.</p>
				</div>
				<div class="unit readonly">
					<h1>Criteria</h1>
					<h2>Criteria() As String</h2>
					<p>Returns the technical reason behind the problem, for example, "Expected 4 but found 2."</p>
				</div>
				<div class="unit readonly">
					<h1>ErrorNumber</h1>
					<h2>ErrorNumber() As Integer</h2>
					<p>Returns the error number of the exception.  For assertion failures, the error code is zero.</p>
				</div>
				<div class="unit readonly">
					<h1>ExceptionClassType</h1>
					<h2>ExceptionClassType() As String</h2>
					<p>Returns name of the class of the exception.  For assertion failures, "UnitTestExceptionKFS" is returned.</p>
				</div>
				<div class="unit readonly">
					<h1>Explanation</h1>
					<h2>Explanation() As String</h2>
					<p>Returns the textual message at the time of the assertion or exception.  Includes the entire message stack.</p>
				</div>
				<div class="unit readonly">
					<h1>Message</h1>
					<h2>Message() As String</h2>
					<p>Returns an explanation of this error.  Includes all available data except the stack trace.</p>
				</div>
				<div class="unit readonly">
					<h1>ScenarioType</h1>
					<h2>ScenarioType() As UnitTestArbiterKFS.UnitTestExceptionScenarios</h2>
					<p>Returns the type of failure that this object represents.  For example, a failed assertion, a caught exception, and an uncaught exception are all possible scenarios.</p>
				</div>
				<div class="unit readonly">
					<h1>Stack</h1>
					<h2>Stack() As String()</h2>
					<p>Returns the runtime stack trace at the time when this exception was raised.</p>
				</div>
			</div>
			
			<h2>Compatibility</h2>
			<div>
				<p>This class is compatible with console applications, and should work on all platforms.</p>
				<p>This class is thread safe.</p>
			</div>
			
			<h2>Notes</h2>
			<div>
				<p>When using this class, don't forget that a UnitTestExceptionKFS represents a generic problem.  It might be an assertion failure, or it might not.  It might be an exception, or it might not.  It might be an uncaught exception, or it might not.  Don't assume what kind of problem a UnitTestExceptionKFS represents.</p>
			</div>
			
			<h2>See Also</h2>
			<div class="hlinks">
				<a href="index.html">Unit Testing Framework Overview</a>
				<a href="UnitTestArbiterKFS.html">UnitTestArbiterKFS</a>
				<a href="UnitTestBaseClassKFS.html">UnitTestBaseClassKFS</a>
				<a href="UnitTestWindowKFS.html">UnitTestWindowKFS</a>
				<a href="http://docs.realsoftware.com/index.php/Introspection">Introspection Module</a>
			</div>
		</div>
	</body>
</html>
